# Generated by Django 4.2.11 on 2024-05-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
