# Generated by Django 4.2.11 on 2024-05-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_courses_course_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_level',
            field=models.CharField(blank=True, choices=[('ADVANCE', 'Advance'), ('INTERMEDIATE', 'Intermediate'), ('BEGINNER', 'Beginner')], max_length=100, null=True),
        ),
    ]
