# Generated by Django 4.2.11 on 2024-05-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_courses_course_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_grade',
        ),
        migrations.AddField(
            model_name='courses',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/course_images/'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='course_grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
