# Generated by Django 4.2.11 on 2024-05-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_courses_course_grade_courses_course_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='course_grade',
        ),
        migrations.AddField(
            model_name='courses',
            name='course_grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
