# Generated by Django 4.2.13 on 2024-05-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_courses_course_image_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_level',
            field=models.CharField(blank=True, choices=[('ALL', 'All'), ('ADVANCE', 'Advance'), ('INTERMEDIATE', 'Intermediate'), ('BEGINNER', 'Beginner')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='number_of_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
